unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-b
set -g base-index 1
set -g pane-base-index 1

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

set -g default-terminal "xterm-ghostty"
set -as terminal-features ",xterm-ghostty:RGB"
set -as terminal-features ",*256col*:RGB"

set -g history-limit 50000
set -g display-time 4000
set -g focus-events on
set -g aggressive-resize on

# theme
source-file ~/.config/tmux/themes/kanagawa-wave.conf
